########################################################################################
#
# MAIN DOOR LIGHT
# 
# 1. light when move in dark
# 2. turn on when closed all lights before bed
# 3. turn on when come back late
# 4. turn off if any strong light is on
#
########################################################################################

# Turn on main door light a while when someone move in dark or main door opened
#-------------------------------------------------------------------------------
- alias : main_door_light_turn_on_when_someone_move_in_dark_or_main_door_opened
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_34ce008d55f1 # main door light
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: group.living_room_and_dining_room_strong_light
        state: 'off'  
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.illumination_34ce008d55f1
            below: '500'  
          - condition: time
            after:  '18:30:00'  
            before: '06:30:00'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00016e2640 # corridor motion sensor
    platform: state
    to: 'on'
  - entity_id: binary_sensor.door_window_sensor_158d0001b77b65  # main door 
    platform: state
    to: 'on'
  - entity_id: group.living_room_and_dining_room_strong_light # strong light off
    platform: state
    to: 'off'

# 2. Turn OFF main door light a while no motion a while or strong light is on 
##---------------------------------------------------------------------------
- alias : main_door_light_turn_off_when_no_motion_or_strong_light_on
  action:
    data:
      entity_id: light.gateway_light_34ce008d55f1  # main door light
    service: light.turn_off
  condition: 
    condition: state
    entity_id: light.gateway_light_34ce008d55f1  # main door light
    state: 'on'  
  trigger:    
  - entity_id: binary_sensor.motion_sensor_158d00016e2640
    platform: state
    to: 'off'
    for:
      minutes: 1
  - entity_id: group.living_room_and_dining_room_strong_light
    platform: state
    from: 'off'
    to: 'on'
     
# ########################################################################################
## 
# RESTART HASSIO
#
# ########################################################################################

## when the restart hass boolean is set to true, restart hass
# -----------------------------------------------------------------------------------------
- alias : restart_hass
  hide_entity: False
  trigger:
    platform: state
    entity_id: input_boolean.restart_hass
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.restart


# ########################################################################################
#
# GOOGLE_HOME
# 
# 1. keep quite at night
#
# ########################################################################################

## adjust google home volume
########################################################################################
- alias : google_home_volume_up_when_morning
  action:
    data:
      volume_level: '0.5'
    service: media_player.volume_set
    entity_id: media_player.google_home
  trigger:
    at: '06:10'
    platform: time  

- alias : google_home_volume_down_when_night
  action:
    data:
      volume_level: '0.3'
    service: media_player.volume_set
    entity_id: media_player.google_home
  trigger:
    at: '21:30'
    platform: time


# ########################################################################################
#
# LIGHT_TROUGH
#
# ########################################################################################

## light_trough_turn_on_when_anyone_home_close_to_sunset
##------------------------------------------------------------
- alias:  light_trough_turn_on_when_anyone_home_close_to_sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:15:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: custom_sensor.anyone_home
        state: 'on'
      - condition: state
        entity_id: switch.wall_switch_left_158d0001a4184a #light trough     
        state: 'off'
  action:
    - service: tts.google_say
      data_template:
        entity_id: media_player.google_home
        message: >
          'Sunset soon, let me turn on light trough for you'
    - delay: '00:00:05'
    - service: switch.turn_on
      entity_id: switch.wall_switch_left_158d0001a4184a #light trough


# light_trough_turn_on_when_wakeup_in_the_morning
##------------------------------------------------------------
- alias : light_trough_turn_on_when_wakeup_in_the_morning
  action:
    - service: tts.google_say
      data_template:
        entity_id: media_player.google_home
        message: >
          'Good morning, a little bit dark now, let me turn on light trough for you'
    - service: switch.turn_on
      data:
        entity_id: switch.wall_switch_left_158d0001a4184a #light trough     
      
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.wall_switch_left_158d0001a4184a #light trough     
        state: 'off'  
      - condition: numeric_state
        entity_id: sensor.illumination_34ce008d55f1
        below: '750'  
      - condition: time
        after:  '05:45:00'  
        before: '09:00:00'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00016e2640 # corridor motion sensor
    from: 'off'
    platform: state
    to: 'on'

# light_trough_turn_off_when_donald_go_to_work
##------------------------------------------------------------
- alias : light_trough_turn_off_when_donald_go_to_work
  action:
    data:
      entity_id: switch.wall_switch_left_158d0001a4184a #light trough     
    service: switch.turn_off
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.wall_switch_left_158d0001a4184a #light trough     
        state: 'on'  
  trigger:
    - platform: time
      at: '07:45:00'


## light_trough_turn_off_when_light_enough
##------------------------------------------------------------
- alias:  light_trough_turn_off_when_light_enough
  trigger:
    - platform: state
      entity_id: switch.wall_switch_right_158d00016c618a # living room light
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: switch.wall_switch_left_158d00016c618a # dining room light
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.wall_switch_left_158d0001a4184a #light trough     
        state: 'on'
      - condition: state
        entity_id: switch.wall_switch_right_158d00016c618a # living room light 
        state: 'on'
      - condition: state
        entity_id: switch.wall_switch_left_158d00016c618a # dining room light
        state: 'on'
  action:
    service: switch.turn_off
    entity_id: switch.wall_switch_left_158d0001a4184a #light trough   

# ###############################################################################
#
# NOTIFY
#
# ###############################################################################

# notify_me_when_main_door_opened
########################################################################################
- alias: notify_me_when_main_door_opened
  action:
    service: telegram_bot.send_message
    data: 
      message: 'Main door opened'
  trigger:    
  - entity_id: binary_sensor.door_window_sensor_158d0001b77b65  #main door
    platform: state
    to: 'on'


########################################################################################
#
# KITCHEN_LIGHTS
#
########################################################################################
- alias: kitchen_light_turn_on_when_someone_move
  trigger: 
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001aa968c # kitchen motion
      to: 'on'
  action:
    - service: light.turn_on 
      data:
        entity_id: group.kitchen_light
        brightness_pct: 100

- alias: kitchen_light_dim_when_idle_a_while
  trigger: 
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001aa968c # bathroom motion
      to: 'off'
      for: 
        minutes: 1
        seconds : 0
  condition:  # if some intended to turn it off..dun turn it on again
    condition: state
    entity_id: group.kitchen_light
    state: 'on'  
  action:
    - service: light.turn_on 
      data:
        entity_id: group.kitchen_light
        brightness_pct: 50

- alias: kitchen_light_turn_off_when_no_one
  trigger: 
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001aa968c # kitchen motion
      to: 'off'
      for: 
        minutes: 2
        seconds : 0
  condition:
    condition: state
    entity_id: group.kitchen_light
    state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: group.kitchen_light

########################################################################################
#
# BATHROOM_LIGHTS
#
# == turn on ==
# 1. door open, turn on
# 2. motion detected, turn on
#
# == turn off ==
# 1. when no motion for a while, dim 50%
# 2. when no motion for a while longer, dim 75%
# 3. when no motion for long idle, turn off the light
# 4. when press the button, turn off light until next open close
#
# [lock] when there is motion detected during door closed, set status 'someone_in_bathroom' 
# is true and suspend all dim and turn off light attempt until door open again
#
########################################################################################
- alias: bathroom_light_turn_on_when_door_open
  trigger: 
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00019f6fef # bathroom door
      to: 'on'
  condition:
    condition: or 
    conditions:
    - condition: numeric_state
      entity_id: light.bathroom_light_L
      value_template: '{% if states.light.bathroom_light_L.state == "on"  %}{{ states.light.bathroom_light_L.attributes.brightness }}{% else %}0{% endif %}'
      below: 255
    - condition: numeric_state
      entity_id: light.bathroom_light_R
      value_template: '{% if states.light.bathroom_light_R.state == "on"  %}{{ states.light.bathroom_light_R.attributes.brightness }}{% else %}0{% endif %}'
      below: 255
  action:
    - service: light.turn_on 
      data:
        entity_id: group.bathroom_light
        brightness_pct: 100


- alias: bathroom_light_turn_on_when_someone_actions
  trigger: 
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001dc14ab # bathroom motion
      to: 'on'
  condition:
    condition: or 
    conditions:
    - condition: numeric_state
      entity_id: light.bathroom_light_L
      value_template: '{% if states.light.bathroom_light_L.state == "on"  %}{{ states.light.bathroom_light_L.attributes.brightness }}{% else %}0{% endif %}'
      below: 255
    - condition: numeric_state
      entity_id: light.bathroom_light_R
      value_template: '{% if states.light.bathroom_light_R.state == "on"  %}{{ states.light.bathroom_light_R.attributes.brightness }}{% else %}0{% endif %}'
      below: 255
  action:
    - service: light.turn_on 
      data:
        entity_id: group.bathroom_light
        brightness_pct: 100

- alias: bathroom_light_dim_when_idle_a_while
  trigger: 
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001dc14ab # bathroom motion
      to: 'off'
      for: 
        seconds: 15
  condition:  # when someone inside, dun dim
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.someone_in_bathroom
        state: 'off'  
      - condition: state  # if some intended to turn it off..dun turn it on again
        entity_id: group.bathroom_light
        state: 'on'  
  action:
    - service: light.turn_on 
      data:
        entity_id: group.bathroom_light
        brightness_pct: 50

- alias: bathroom_light_dim_when_idle_a_longer
  trigger: 
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001dc14ab # bathroom motion
      to: 'off'
      for: 
        minutes: 0
        seconds: 30
  condition:  # when someone inside, dun dim
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.someone_in_bathroom
        state: 'off'  
      - condition: state  # if some intended to turn it off..dun turn it on again
        entity_id: group.bathroom_light
        state: 'on'  
  action:
    - service: light.turn_on 
      data:
        entity_id: group.bathroom_light
        brightness_pct: 25

- alias: bathroom_light_turn_off_while_long_idle
  trigger: 
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001dc14ab # bathroom motion
      to: 'off'
      for: 
        minutes: 0
        seconds: 45
  condition:  # when someone inside, dun dim
    condition: state
    entity_id: input_boolean.someone_in_bathroom
    state: 'off'  
  action:
    - service: light.turn_off
      data:
        entity_id: group.bathroom_light

- alias: bathroom_light_turn_off_while_long_idle_double_check
  trigger: 
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001dc14ab # bathroom motion
      to: 'off'
      for: 
        minutes: 1
        seconds: 0
  condition:  # when someone inside, dun dim
    condition: state
    entity_id: input_boolean.someone_in_bathroom
    state: 'off'  
  action:
    - service: light.turn_off
      data:
        entity_id: group.bathroom_light

 # When motion triggered and door is close, set someone_in_bathroom is true
 # ---------------------------------------------------------------------------
- alias: someone_in_bathroom_turn_off_when_door_open
  trigger: 
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00019f6fef # bathroom motion
      to: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.someone_in_bathroom

 # When motion triggered and door is close, set someone_in_bathroom is true
 # ---------------------------------------------------------------------------
- alias: someone_in_bathroom_turn_on_when_motion_after_door_close
  trigger: 
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001dc14ab # bathroom motion
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d00019f6fef # bathroom door
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.someone_in_bathroom

#
# After door is closed, motion detected for a while
# It means someone inside bathroom
#---------------------------------------------------
- alias: someone_in_bathroom_turn_on_when_motion_continue_a_while
  trigger: 
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00019f6fef # bathroom door
        to: 'off'
        for: 
          seconds: 135
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.someone_in_bathroom
      state: 'off'
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d0001dc14ab # bathroom motion
      state: 'on'
    - condition: template # bathroom motion on closed more than 90sec
      value_template: '{{ (as_timestamp(now())-as_timestamp(states.binary_sensor.motion_sensor_158d0001dc14ab.last_updated)) > 135}}'
  action:
    - service: input_boolean.turn_on
      data:
          entity_id: input_boolean.someone_in_bathroom


########################################################################################
#
# Donald Bedroom side light
#
########################################################################################
- alias: toggle_donald_bedroom_side_light_when_click_donald_side_bed_button
  action:
    service: light.toggle
    data:
        entity_id: light.donald_bedroom_side_light
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00022c382e # Donald bed side button
      click_type: single

#- alias: set_donald_bedroom_side_color_to_normal_color
#  action:
#    service: light.toggle
#    data:
#        entity_id: light.donald_bedroom_side_light
#        rgb_color: [255,180,100]
#  trigger:
#    platform: state
#    entity_id: light.donald_bedroom_side_light
#    to: 'on'

########################################################################################
#
# ALL LIGHTS
#
########################################################################################

# turn_off_all_lights_when_long_press_donald_side_bed_button
########################################################################################
- alias: all_lights_turn_off_when_long_press_donald_side_bed_button
  action:
    service: script.turn_off_all_lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00022c382e # Donald bed side button
      click_type: long_click_press

# turn_off_all_lights_when_no_one_home
########################################################################################
- alias: all_lights_turn_off_when_no_one_home
  action:
    service: script.turn_off_all_lights
  condition:
    condition: or
    conditions: 
      - condition: state
        entity_id: group.all_lights
        state: 'on'
      - condition: state
        entity_id: group.all_switches
        state: 'on'
      - condition: state  # no one moving for a while
        entity_id: group.default_motion
        state: 'off'
  trigger:    
  - entity_id: custom_sensor.anyone_home
    platform: state
    to: 'off'
    for:
      minutes: 30


###############################################################################
#
# TTS
#
###############################################################################
- alias: tts_good_morning_in_weekday
  trigger:
    - platform: time
      at: '06:15:00'
    - platform: time
      at: '07:00:00'
    - platform: time
      at: '07:10:00'
    - platform: time
      at: '07:20:00'
    - platform: time
      at: '07:45:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: custom_sensor.anyone_home
        state: 'on'
  action:
    - service: tts.google_say
      data_template:
        entity_id: media_player.google_home
        message: >
          {% set hour = now().strftime("%H") %}
          {% set minutes = now().strftime("%M") %}
          {% set weekday_full_name = now().strftime("%A") %}
          {% set month_full_name = now().strftime("%B") %}
          {% set day = now().strftime("%-d") %}
          {% set weekday = now().strftime("%w") %}
          {% if hour | int < 12 %}
          Good morning. Today is {{ weekday_full_name }} {{ month_full_name }} the
            {% if day | int == 1 or day | int == 21 or day | int == 31 %}
              {{ day }}st
            {% elif day | int == 2 or day | int == 22 %}
              {{ day }}nd
            {% elif day | int == 3 or day | int == 23 %}
              {{ day }}rd
            {% else %}
              {{ day }}th
            {% endif %}.
          {% elif hour | int < 18 %}
          Good afternoon.
          {% else %}
          Good evening.
          {% endif %}
          Right now is {{hour}} {{minutes}} 


###############################################################################
#
# CUSTOM SENSOR
#
###############################################################################

- alias: people_home_custom_sensor_regular_scan
  trigger:
    platform: time
    minutes: 1
    seconds: 00
  action:
    - service: python_script.count_people_home
    - service: python_script.anyone_home
